// Generated by scripts/generate-upstream-sw.mjs. Do not edit directly.
// shell 0c4e73ced67c: 318 assets, 2.7 MiB local
const VERSION = '0c4e73ced67c';
const SHELL_CACHE = 'svgmap-shell-' + VERSION;
const RUNTIME_CACHE = 'svgmap-runtime-' + VERSION;
const DYNAMIC_CACHE = 'svgmap-dynamic-v2';
const TILE_CACHE = 'svgmap-tiles-v2';
const META_CACHE = 'svgmap-cache-meta-v1';
const SHEET_URL = "https://docs.google.com/spreadsheets/d/1RR_LtusyFPtp4Ut09Qc2Aoe92-Ocv4Dn1NZH73JOmcA/export?format=csv";
const SHELL = [
  "/svgmap.html",
  "/svgmapAppLayers/Container.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/data/municipalities-index.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/current-location-pin.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/river-level-advisory.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/river-level-danger.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/river-level-evacuation.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/river-level-normal.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/river-level-stale.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/river-level-unknown.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/river-webcam.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/road-closure-cleared.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/road-closure-closed.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/road-closure-flooded.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/road-closure-restricted.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/road-closure-unknown.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/shelter-closed.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/shelter-default.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/shelter-full.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/shelter-limited.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/shelter-open.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/team-active.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/team-attention.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/team-completed.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/team-planned.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/icons/team-standby.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/evacuation/evacuationDetail.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/evacuation/evacuationLayer.html",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/evacuation/evacuationLayer.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/evacuation/layer.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/portable-network/runtime.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/portable-network/safeFetch.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/representative-pins/densityPointFormat.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/representative-pins/mapMessages.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/representative-pins/observationFreshness.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/representative-pins/pinLayerProfiles.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/representative-pins/propertyModal.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/representative-pins/qtctFeatureEngine.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/representative-pins/representativePinsCore.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/representative-pins/representativePinsPortable.html",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/representative-pins/representativePinsPortable.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/representative-pins/runtime.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/representative-pins/runtimeCache.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/svgmap-slawa-client/InterWindowMessaging.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/svgmap-slawa-client/libs/SvgMapElementType.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/svgmap-slawa-client/libs/TransformLib.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/svgmap-slawa-client/libs/UtilFuncs.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/svgmap-slawa-client/runtime.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/svgmap-slawa-client/svgMapLayerLib.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/evacuation/map/layers/portable/svgmap-slawa-client/svgMapSandboxLayerLib.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/flood-warning/floodWarningDetail.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/flood-warning/floodWarningLayer.html",
  "/svgmapAppLayers/appLayers/svg3-bosai/flood-warning/floodWarningLayer.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/flood-warning/floodWarningLayer.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/flood-warning/jmaWarnings.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/flood-warning/layer.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/flood-warning/warning-advisory.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/flood-warning/warning-emergency.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/flood-warning/warning-unknown.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/flood-warning/warning-warning.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/hazard/hazardLayer.html",
  "/svgmapAppLayers/appLayers/svg3-bosai/hazard/hazardLayer.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/hazard/index.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/current-location-pin.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/river-level-advisory.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/river-level-danger.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/river-level-evacuation.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/river-level-normal.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/river-level-stale.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/river-level-unknown.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/river-webcam.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/road-closure-cleared.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/road-closure-closed.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/road-closure-flooded.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/road-closure-restricted.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/road-closure-unknown.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/shelter-closed.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/shelter-default.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/shelter-full.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/shelter-limited.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/shelter-open.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/team-active.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/team-attention.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/team-completed.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/team-planned.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/icons/team-standby.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/current-location-pin.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/river-level-advisory.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/river-level-danger.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/river-level-evacuation.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/river-level-normal.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/river-level-stale.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/river-level-unknown.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/river-webcam.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/road-closure-cleared.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/road-closure-closed.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/road-closure-flooded.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/road-closure-restricted.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/road-closure-unknown.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/shelter-closed.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/shelter-default.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/shelter-full.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/shelter-limited.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/shelter-open.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/team-active.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/team-attention.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/team-completed.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/team-planned.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/icons/team-standby.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/japan-river-webcams/layer.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/japan-river-webcams/webcam-runtime-policy.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/japan-river-webcams/webcamDetail.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/japan-river-webcams/webcamLayer.html",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/japan-river-webcams/webcamLayer.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/representative-pins/densityPointFormat.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/representative-pins/mapMessages.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/representative-pins/observationFreshness.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/representative-pins/pinLayerProfiles.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/representative-pins/propertyModal.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/representative-pins/qtctFeatureEngine.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/representative-pins/representativePinsCore.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/representative-pins/representativePinsPortable.html",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/representative-pins/representativePinsPortable.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/representative-pins/runtime.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/representative-pins/runtimeCache.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/svgmap-slawa-client/InterWindowMessaging.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/svgmap-slawa-client/libs/SvgMapElementType.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/svgmap-slawa-client/libs/TransformLib.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/svgmap-slawa-client/libs/UtilFuncs.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/svgmap-slawa-client/runtime.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/svgmap-slawa-client/svgMapLayerLib.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/japan-river-webcams/map/layers/portable/svgmap-slawa-client/svgMapSandboxLayerLib.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/portable-network/runtime.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/portable-network/safeFetch.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/representative-pins/densityPointFormat.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/representative-pins/mapMessages.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/representative-pins/observationFreshness.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/representative-pins/pinLayerProfiles.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/representative-pins/propertyModal.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/representative-pins/qtctFeatureEngine.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/representative-pins/representativePinsCore.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/representative-pins/representativePinsPortable.html",
  "/svgmapAppLayers/appLayers/svg3-bosai/representative-pins/representativePinsPortable.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/representative-pins/runtime.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/representative-pins/runtimeCache.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/svgmap-slawa-client/InterWindowMessaging.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/svgmap-slawa-client/libs/SvgMapElementType.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/svgmap-slawa-client/libs/TransformLib.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/svgmap-slawa-client/libs/UtilFuncs.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/svgmap-slawa-client/runtime.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/svgmap-slawa-client/svgMapLayerLib.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/svgmap-slawa-client/svgMapSandboxLayerLib.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/current-location-pin.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/river-level-advisory.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/river-level-danger.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/river-level-evacuation.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/river-level-normal.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/river-level-stale.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/river-level-unknown.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/river-webcam.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/road-closure-cleared.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/road-closure-closed.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/road-closure-flooded.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/road-closure-restricted.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/road-closure-unknown.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/shelter-closed.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/shelter-default.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/shelter-full.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/shelter-limited.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/shelter-open.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/team-active.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/team-attention.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/team-completed.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/team-planned.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/icons/team-standby.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/representative-pins/densityPointFormat.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/representative-pins/mapMessages.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/representative-pins/observationFreshness.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/representative-pins/pinLayerProfiles.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/representative-pins/propertyModal.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/representative-pins/qtctFeatureEngine.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/representative-pins/representativePinsCore.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/representative-pins/representativePinsPortable.html",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/representative-pins/representativePinsPortable.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/representative-pins/runtime.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/representative-pins/runtimeCache.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/svgmap-slawa-client/InterWindowMessaging.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/svgmap-slawa-client/libs/SvgMapElementType.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/svgmap-slawa-client/libs/TransformLib.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/svgmap-slawa-client/libs/UtilFuncs.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/svgmap-slawa-client/runtime.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/svgmap-slawa-client/svgMapLayerLib.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/svgmap-slawa-client/svgMapSandboxLayerLib.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/team-activity/appLayersAdmin.html",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/team-activity/layer.package.json",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/team-activity/teamActivityAreaLayer.html",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/team-activity/teamActivityAreaLayer.svg",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/team-activity/teamActivityCsv.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/team-activity/teamActivityDetail.js",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/team-activity/teamActivityLayer.html",
  "/svgmapAppLayers/appLayers/svg3-bosai/team-activity/map/layers/portable/team-activity/teamActivityLayer.svg",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/ClientSideQTCT.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/CsvMapper.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/FetchTextProgress.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/LocalDBFileManager.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/QTCTLayerRenderer.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/csvEditMainPanel.css",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/csvInputUI_r20.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/csvInputUI_r20.xhtml",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/csvUI_r20.html",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/csvXhr_r20.svg",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/externalCsvPhotoPopup.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/fileAdminPanel.html",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/geojson2csvExtension.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/gsiGeoCoder.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/icon_r15/mappinL0.png",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/icon_r15/mappinL1.png",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/icon_r15/mappinL2.png",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/icon_r15/mappinL3.png",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/icon_r15/mappinL4.png",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/icon_r15/mappinL5.png",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/imageMetadataExtension.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/imageMetadataInputUIExtension.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/indexDBpromise.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/mountainCsvBuilder.html",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/tabUi.css",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/tinyFileManagerForCsv.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/unzipit.module.js",
  "/svgmapAppLayers/authoringLayers/local/csvLayer/zip.min.js",
  "/svgmapjs/3D_extension/SVGMapLv0.1_CesiumWrapper_r4module.js",
  "/svgmapjs/3D_extension/cesiumWindow4.html",
  "/svgmapjs/3D_extension/cesiumWindow4_module.js",
  "/svgmapjs/3D_extension/getProviderViewModels_module.js",
  "/svgmapjs/CorsProxyModule.js",
  "/svgmapjs/InterWindowMessaging.js",
  "/svgmapjs/SVGMapCustomLayersManagerApp_r3module.js",
  "/svgmapjs/SVGMapCustomLayersManagerClient.js",
  "/svgmapjs/SVGMapCustomLayersManager_r3module.html",
  "/svgmapjs/SVGMapLv0.1_Authoring_r8_module.js",
  "/svgmapjs/SVGMapLv0.1_Class_r18module.js",
  "/svgmapjs/SVGMapLv0.1_CustomLayersManager_r3module.js",
  "/svgmapjs/SVGMapLv0.1_GIS_r4_module.js",
  "/svgmapjs/SVGMapLv0.1_LayerUI_r6module.js",
  "/svgmapjs/SVGMapLv0.1_r18module.js",
  "/svgmapjs/customLayerManagerExtension.js",
  "/svgmapjs/libs/BuiltinIcons.js",
  "/svgmapjs/libs/CollidedImagesGetter.js",
  "/svgmapjs/libs/CustomHitTester.js",
  "/svgmapjs/libs/CustomModal.js",
  "/svgmapjs/libs/EssentialUIs.js",
  "/svgmapjs/libs/GPS.js",
  "/svgmapjs/libs/GeometryCapture.js",
  "/svgmapjs/libs/GlobalMessageDisplay.js",
  "/svgmapjs/libs/HashGen.js",
  "/svgmapjs/libs/IframeAdapter4SLaWA.js",
  "/svgmapjs/libs/ImgRenderer.js",
  "/svgmapjs/libs/KMLParser.js",
  "/svgmapjs/libs/LayerManager.js",
  "/svgmapjs/libs/LayerSpecificWebAppHandler.js",
  "/svgmapjs/libs/LayerStyleCustomizer.js",
  "/svgmapjs/libs/LinkedDocOp.js",
  "/svgmapjs/libs/MapTicker.js",
  "/svgmapjs/libs/MapViewerProps.js",
  "/svgmapjs/libs/PathHitTester.js",
  "/svgmapjs/libs/PathRenderer.js",
  "/svgmapjs/libs/PoiHitTester.js",
  "/svgmapjs/libs/ProxyManager.js",
  "/svgmapjs/libs/ResourceLoadingObserver.js",
  "/svgmapjs/libs/ResumeManager.js",
  "/svgmapjs/libs/SVGMapSerializer_obsoluted.js",
  "/svgmapjs/libs/SVGMapVectorFileRenderer.js",
  "/svgmapjs/libs/SandboxWrapper.js",
  "/svgmapjs/libs/ShowPoiProperty.js",
  "/svgmapjs/libs/SvgImageProps.js",
  "/svgmapjs/libs/SvgMapElementType.js",
  "/svgmapjs/libs/SvgStyle.js",
  "/svgmapjs/libs/SvgStyleEditor.js",
  "/svgmapjs/libs/TernarySimultaneousEquationsSolution.js",
  "/svgmapjs/libs/TransformLib.js",
  "/svgmapjs/libs/UAtester.js",
  "/svgmapjs/libs/UtilFuncs.js",
  "/svgmapjs/libs/ZoomPanManager.js",
  "/svgmapjs/svgMapLayerLib.js",
  "/svgmapjs/svgMapSandboxLayerLib.js",
  "/svgmapjs/tests/unittest/EssentialUIs.test.js",
  "/svgmapjs/tests/unittest/GPS.test.js",
  "/svgmapjs/tests/unittest/GeoMetryCapture.test.js",
  "/svgmapjs/tests/unittest/MapTicker.test.js",
  "/svgmapjs/tests/unittest/PathHitTester.test.js",
  "/svgmapjs/tests/unittest/PathRenderer.test.js",
  "/svgmapjs/tests/unittest/PoiHitTester.test.js",
  "/svgmapjs/tests/unittest/ProxyManager.test.js",
  "/svgmapjs/tests/unittest/ResourceLoadingObserver.test.js",
  "/svgmapjs/tests/unittest/ResumeManager.test.js",
  "/svgmapjs/tests/unittest/SVGMapLv0.1_Class_r18module.test.js",
  "/svgmapjs/tests/unittest/SVGMapLv0.1_GIS.test.js",
  "/svgmapjs/tests/unittest/SandboxWrapper.test.js",
  "/svgmapjs/tests/unittest/ShowPoiProperty.test.js",
  "/svgmapjs/tests/unittest/SvgImageProps.test.js",
  "/svgmapjs/tests/unittest/SvgStyle.test.js",
  "/svgmapjs/tests/unittest/TernarySimultaneousEquationsSolution.test.js",
  "/svgmapjs/tests/unittest/TestResetUtility.js",
  "/svgmapjs/tests/unittest/TransformLib.test.js",
  "/svgmapjs/tests/unittest/UAtester.test.js",
  "/svgmapjs/tests/unittest/UtilFuncs.test.js",
  "/svgmapjs/tests/unittest/ZoomPanManager.test.js",
  "/svgmapjs/tests/unittest/resources/mock.html",
  "/svgmapjs/tests/unittest/resources/mockParamerters.js",
  "/svgmapjs/tests/unittest/svgMapSandboxLayerLib.test.js",
  "/layerListStyle.css",
  "/svgmap-bootstrap.js",
  "https://unpkg.com/jsts@1.6.1/dist/jsts.min.js",
  "https://raw.githubusercontent.com/svgmap/svgMapDemo/main/img/zoomup.png",
  "https://raw.githubusercontent.com/svgmap/svgMapDemo/main/img/zoomdown.png",
  "https://raw.githubusercontent.com/svgmap/svgMapDemo/main/img/gps.png",
  "https://raw.githubusercontent.com/svgmap/svgMapDemo/main/img/permaLink.png",
  "https://raw.githubusercontent.com/svgmap/svgMapDemo/main/img/Xcursor.png",
  "https://raw.githubusercontent.com/svgmap/svgMapDemo/main/img/vscale.png"
];
const MAX_RUNTIME_ENTRIES = 800;
const MAX_DYNAMIC_ENTRIES = 50;
const MAX_TILE_ENTRIES = 1500;

const notifyClients = (message) => self.clients.matchAll({ type: 'window', includeUncontrolled: true })
  .then((clients) => clients.forEach((client) => client.postMessage(message)));

const trimEntries = async (cacheName, maximum) => {
  const cache = await caches.open(cacheName);
  const keys = await cache.keys();
  const expired = keys.slice(0, Math.max(0, keys.length - maximum));
  const meta = await caches.open(META_CACHE);
  await Promise.all(expired.map(async (key) => {
    await Promise.all([cache.delete(key), meta.delete(metadataRequest(key))]);
  }));
};

const metadataRequest = (request) => new Request(
  self.location.origin + '/__svgmap_cache_meta__?url=' + encodeURIComponent(request.url)
);

const store = async (cacheName, request, response, maximum) => {
  if (!(response.ok || response.type === 'opaque')) return;
  const cache = await caches.open(cacheName);
  await cache.put(request, response.clone());
  const meta = await caches.open(META_CACHE);
  await meta.put(metadataRequest(request), new Response(new Date().toISOString()));
  void trimEntries(cacheName, maximum);
};

const storedAt = async (request) => {
  const meta = await caches.open(META_CACHE);
  return (await meta.match(metadataRequest(request)))?.text() || null;
};

const fetchWithTimeout = async (request, milliseconds = 7000) => {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), milliseconds);
  try {
    return await fetch(new Request(request, { signal: controller.signal }));
  } finally {
    clearTimeout(timer);
  }
};

const networkFirst = async (request, cacheName, maximum, label) => {
  try {
    const response = await fetchWithTimeout(request);
    if (!response.ok && response.type !== 'opaque') throw new Error('HTTP ' + response.status);
    await store(cacheName, request, response, maximum);
    void notifyClients({ type: 'SVG3_CACHE_FRESH', label });
    return response;
  } catch (error) {
    const cached = await caches.match(request, { cacheName });
    if (!cached) throw error;
    void notifyClients({
      type: 'SVG3_CACHE_FALLBACK',
      label,
      cachedAt: await storedAt(request),
    });
    return cached;
  }
};

const cacheFirst = async (request, cacheName, maximum) => {
  const cached = await caches.match(request, { cacheName });
  if (cached) return cached;
  const response = await fetch(request);
  await store(cacheName, request, response, maximum);
  return response;
};

const precache = async (cache, url) => {
  const request = new Request(url, { cache: 'reload' });
  try {
    const response = await fetchWithTimeout(request, 10000);
    if (response.ok || response.type === 'opaque') await cache.put(request, response);
  } catch (_error) {
    // One unavailable upstream icon must not prevent the offline shell from activating.
  }
};

const isTile = (url) => [
  'tile.openstreetmap.org',
  'a.tile.openstreetmap.org',
  'b.tile.openstreetmap.org',
  'c.tile.openstreetmap.org',
  'tile.openstreetmap.jp',
  'cyberjapandata.gsi.go.jp',
  'disaportal.gsi.go.jp',
  'disaportaldata.gsi.go.jp',
].includes(url.hostname) && /\.(png|jpg|jpeg|webp|gif|pbf)$/.test(url.pathname.toLowerCase());

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL_CACHE);
    await Promise.allSettled(SHELL.map((url) => precache(cache, url)));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const name of await caches.keys()) {
      if ((name.startsWith('svgmap-shell-') && name !== SHELL_CACHE)
        || (name.startsWith('svgmap-runtime-') && name !== RUNTIME_CACHE)) {
        await caches.delete(name);
      }
    }
    await self.clients.claim();
    void notifyClients({ type: 'SVG3_CACHE_READY', version: VERSION });
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        return await fetch(request);
      } catch (_error) {
        return (await caches.match('/svgmap.html', { cacheName: SHELL_CACHE }))
          || Response.error();
      }
    })());
    return;
  }

  if (request.url === SHEET_URL) {
    event.respondWith(networkFirst(request, DYNAMIC_CACHE, MAX_DYNAMIC_ENTRIES, 'Google Sheets CSV'));
    return;
  }

  if (url.origin !== self.location.origin) {
    if (isTile(url)) event.respondWith(cacheFirst(request, TILE_CACHE, MAX_TILE_ENTRIES));
    else if (SHELL.includes(request.url)) event.respondWith(cacheFirst(request, SHELL_CACHE, SHELL.length));
    return;
  }

  if (url.pathname === '/api/drive-image') {
    event.respondWith(networkFirst(request, DYNAMIC_CACHE, MAX_DYNAMIC_ENTRIES, 'Google Drive写真'));
    return;
  }

  event.respondWith((async () => {
    const shellHit = await caches.match(request, { cacheName: SHELL_CACHE });
    if (shellHit) return shellHit;
    const cached = await caches.match(request, { cacheName: RUNTIME_CACHE });
    const update = fetch(request).then(async (response) => {
      await store(RUNTIME_CACHE, request, response, MAX_RUNTIME_ENTRIES);
      return response;
    });
    return cached || update;
  })());
});
